Librerias

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Temporales

In [2]:
df=pd.read_csv("dataFeat00.csv")

In [3]:
df.head()

0_Absolute energy  0_Area under the curve  0_Autocorrelation  0_Centroid  \
0        142365.0174               286.28765        142365.0174  148.380897   
1        200857.1379               472.59640        200857.1379  150.243476   
2         17428.5243               104.19660         17428.5243   60.685034   
3        143933.2155               492.42680        143933.2155  355.427154   
4         29660.6292               142.08075         29660.6292   87.713568   

   0_Entropy  0_Mean absolute diff  0_Mean diff  0_Median absolute diff  \
0   0.536766              0.068391     0.000006                     0.0   
1   0.608193              0.072566    -0.000019                     0.0   
2   0.605717              0.061699     0.000023                     0.0   
3   0.488515              0.036480     0.000004                     0.0   
4   0.611549              0.075822     0.000016                     0.0   

   0_Median diff  0_Negative turning points  ...  0_Negative turning points.5  \
0            0.0                      121.0  ...                         30.0   
1            0.0                        3.0  ...                        145.0   
2            0.0                      136.0  ...                         11.0   
3            0.0                      325.0  ...                        174.0   
4            0.0                      152.0  ...                         19.0   

   0_Neighbourhood peaks.5  0_Peak to peak distance.5  \
0                     12.0                      16.58   
1                     32.0                      10.02   
2                     12.0                       2.47   
3                     33.0                      12.17   
4                     22.0                       2.12   

   0_Positive turning points.5  0_Signal distance.5     0_Slope.5  \
0                         26.0         30772.740382  1.959646e-06   
1                        133.0         30221.612917 -2.278738e-06   
2                         18.0         14564.629231 -8.298997e-07   
3                        170.0         79885.731347  2.104734e-06   
4                         27.0         16932.717928 -4.184387e-07   

   0_Sum absolute diff.5  0_Total energy.5  0_Zero crossing rate.5  out  
0                 267.32         36.060530                   422.0    1  
1                 395.44         81.343710                   839.0    1  
2                  95.32          4.821618                   289.0    1  
3                 492.84         29.625755                  1309.0    1  
4                 141.91          4.430320                   483.0    1  

[5 rows x 109 columns]

In [9]:
X=df.loc[:, df.columns != "out"] #asignandole todas las variables menos la salida
y=df['out']

In [11]:

#X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0)

In [12]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0)
clf=RandomForestClassifier(random_state=100, n_estimators=50)

In [13]:
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=100)

In [16]:
predictions=clf.predict(X_test)
print(predictions)

[0 1 0 0]


In [17]:
cm = confusion_matrix(y_test, predictions).ravel()

In [19]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.50      0.67         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4



# Con statistical

In [20]:
df=pd.read_csv("dataFeatStats.csv")

In [21]:
df.head()

0_ECDF_0  0_ECDF_1  0_ECDF_2  0_ECDF_3  0_ECDF_4  0_ECDF_5  0_ECDF_6  \
0  0.000033  0.000065  0.000098  0.000130  0.000163  0.000195  0.000228   
1  0.000069  0.000137  0.000206  0.000275  0.000343  0.000412  0.000481   
2  0.000033  0.000066  0.000099  0.000132  0.000166  0.000199  0.000232   
3  0.000013  0.000025  0.000038  0.000050  0.000063  0.000075  0.000088   
4  0.000059  0.000118  0.000177  0.000236  0.000295  0.000354  0.000413   

   0_ECDF_7  0_ECDF_8  0_ECDF_9  ...  0_Mean.5  0_Mean absolute deviation.5  \
0  0.000260  0.000293  0.000325  ...  0.016680                     0.248134   
1  0.000549  0.000618  0.000687  ... -0.017582                     0.154211   
2  0.000265  0.000298  0.000331  ...  0.068779                     0.531053   
3  0.000100  0.000113  0.000125  ...  0.004184                     0.242517   
4  0.000473  0.000532  0.000591  ... -0.019009                     0.147293   

   0_Median.5  0_Median absolute deviation.5  0_Min.5  0_Root mean square.5  \
0        0.00                           0.06    -6.52              0.600494   
1       -0.01                           0.12    -1.25              0.219574   
2        0.00                           0.20    -4.74              0.901893   
3        0.00                           0.09    -2.75              0.544292   
4        0.00                           0.10    -1.08              0.210477   

   0_Skewness.5  0_Standard deviation.5  0_Variance.5  out  
0      3.286097                0.600263      0.360315    1  
1     -0.154691                0.218869      0.047904    1  
2      1.062213                0.899266      0.808680    1  
3      4.218091                0.544276      0.296236    1  
4     -0.561748                0.209617      0.043939    1  

[5 rows x 217 columns]

In [23]:
X=df.loc[:, df.columns != "out"] #asignandole todas las variables menos la salida
y=df['out']

In [51]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2,random_state=0, shuffle=True)
clf=RandomForestClassifier(random_state=100, n_estimators=100)

In [52]:
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=100)

In [53]:
predictions=clf.predict(X_test)
print(predictions)

[0 0 1 0]


In [54]:
cm = confusion_matrix(y_test, predictions).ravel()
cm

array([1, 1, 2, 0], dtype=int64)

In [55]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.00      0.00      0.00         2

    accuracy                           0.25         4
   macro avg       0.17      0.25      0.20         4
weighted avg       0.17      0.25      0.20         4



# Espectrales

In [60]:
df=pd.read_csv("dataFeatSpect.csv")

In [61]:
X=df.loc[:, df.columns != "out"] #asignandole todas las variables menos la salida
y=df['out']

In [65]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2,random_state=0, shuffle=True)
clf=RandomForestClassifier(random_state=100, n_estimators=100)

In [66]:
clf.fit(X_train,y_train)

RandomForestClassifier(random_state=100)

In [67]:
predictions=clf.predict(X_test)
print(predictions)

[0 0 0 0]


In [68]:
cm = confusion_matrix(y_test, predictions).ravel()
cm

array([2, 0, 2, 0], dtype=int64)

In [69]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       0.00      0.00      0.00         2

    accuracy                           0.50         4
   macro avg       0.25      0.50      0.33         4
weighted avg       0.25      0.50      0.33         4



D:\Users\Esteban\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\Esteban\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\Esteban\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
